; This file was auto-generated by drush make
core = 7.x

api = 2
projects[drupal][version] = "7.23"

; Modules
projects[views_bulk_operations][version] = "3.1"

projects[addressfield][version] = "1.0-beta4"

projects[admin_menu][version] = "3.0-rc4"

projects[admin_views][version] = "1.2"

projects[ctools][version] = "1.3"

projects[context][version] = "3.1"

projects[context_no_title][version] = "1.0-beta3"

projects[context_omega][version] = "1.1"

projects[date][version] = "2.6"

projects[devel][version] = "1.3"

projects[emfield][version] = "1.0-alpha2"

projects[entity][version] = "1.2"

projects[features][version] = "2.0"

projects[file_entity][version] = "2.0-alpha3"

projects[google_analytics][version] = "1.4"

projects[honeypot][version] = "1.15"

projects[job_scheduler][version] = "2.0-alpha3"

projects[jquery_update][version] = "2.3"

projects[libraries][version] = "1.0"

projects[menu_attributes][version] = "1.0-rc2"

projects[menu_block][version] = "2.3"

projects[module_filter][version] = "1.8"

projects[references][version] = "2.1"

projects[pathauto][version] = "1.2"

projects[publish_button][version] = "1.0-beta8"

projects[rules][version] = "2.5"

projects[search_config][version] = "1.0"

projects[security_review][version] = "1.1"

projects[semanticviews][version] = "1.x-dev"

projects[special_menu_items][version] = "2.0"

projects[token][version] = "1.5"

projects[views][version] = "3.7"

projects[views_php][version] = "1.x-dev"

projects[webform][version] = "3.19"

projects[workbench][version] = "1.2"

projects[xmlsitemap][version] = "2.0-rc2"

; Themes
projects[adminimal_theme][version] = "1.x-dev"

projects[omega][version] = "3.0"
